import type { AdminHelp } from '@/lib/adminLayout'

/** English help texts for the admin panel. The German originals are in src/lib/adminLayout.ts. */

const SLUG_HELP = 'Part of the web address. Lowercase letters, digits and hyphens only, e.g. “deutschkurs-wien”. Do not change it after publishing — old links would lead nowhere.'
const STATUS_HELP = 'Decides whether the entry is on the website. Editors: “Draft” or “In review”. Only the board can publish and archive.'
const BUNDESLAND_HELP = 'Fill in only if the entry concerns one particular federal state.'
const ORDER_HELP = 'Smaller number = further up.'
const ICON_HELP = 'Name of an icon from lucide.dev, e.g. “home” or “briefcase”. Leave empty for the default icon.'
const LAST_REVIEWED_HELP = 'Shown on the page as “Last reviewed: DD.MM.YYYY”. Set it again after every content check.'
const INTERVAL_HELP = 'After this many months the entry appears on the admin start page under “Review overdue”.'
const SOURCE_HELP = 'Link to the official source, e.g. oesterreich.gv.at. Shown below the text.'

export const en: AdminHelp = {
  collections: {
    news: {
      title: 'Headline of the article. Enter it separately for each language (language switcher at the top).',
      slug: SLUG_HELP,
      excerpt: 'Two to three sentences, 200 characters at most. Appears in the overview and in search engines.',
      body: 'The text of the article.',
      coverImage: 'Image above the article and in the overview. Landscape format, at least 1200 pixels wide.',
      category: 'Assigns the article to a section. Visitors can filter by it.',
      author: 'Name shown with the article. Leave empty if no name should be given.',
      publishedAt: 'Date shown with the article; it also sets the order. Empty = today.',
      bundesland: BUNDESLAND_HELP,
      featured: 'Featured articles are at the very top of the news overview.',
      reviewStatus: STATUS_HELP,
    },
    events: {
      title: 'Name of the event. Enter it separately for each language.',
      slug: SLUG_HELP,
      description: 'What happens, who it is for, what to bring.',
      coverImage: 'Image for the event. Landscape format.',
      category: 'Type of event. Visitors can filter by it.',
      startDate: 'Date and time it starts. After that moment the event moves to “Past”.',
      endDate: 'Optional. Leave empty if there is no fixed end.',
      locationName: 'Name of the venue, e.g. “Volkshochschule Ottakring”.',
      address: 'Street, house number, postcode, town.',
      bundesland: BUNDESLAND_HELP,
      isOnline: 'Tick if the event takes place online. Venue and address can then stay empty.',
      registrationUrl: 'Full address (https://…) of the registration page. The website only shows this link — it does not take registrations itself.',
      capacity: 'Number of places. Only displayed, not counted down.',
      isFree: 'Tick if taking part costs nothing.',
      reviewStatus: STATUS_HELP,
    },
    'guide-articles': {
      title: 'Headline of the article. Enter it separately for each language.',
      slug: SLUG_HELP,
      topic: 'The Austria Guide topic the article appears under.',
      excerpt: 'One or two sentences for the overview.',
      body: 'The text of the article. Steps and deadlines as a list where possible.',
      coverImage: 'Optional image above the article.',
      lastReviewedAt: LAST_REVIEWED_HELP,
      reviewIntervalMonths: INTERVAL_HELP,
      officialSourceUrl: SOURCE_HELP,
      relatedServices: 'Services of the association that fit this article. Shown below the text as “Related”.',
      relatedRoadmaps: 'Roadmaps that fit this article. Shown below the text as “Related”.',
      relatedExperts: 'Experts who advise on this topic. Shown below the text as “Related”.',
      reviewStatus: STATUS_HELP,
    },
    roadmaps: {
      title: 'Name of the roadmap, e.g. “Arriving and registering”. Enter it separately for each language.',
      slug: SLUG_HELP,
      description: 'One or two sentences: who this roadmap is for and what is done at the end.',
      icon: ICON_HELP,
      quizMatches: 'For which situations is this roadmap the right answer? The quiz “What is my situation?” is only offered once every possible answer leads to at least one published roadmap.',
      lastReviewedAt: LAST_REVIEWED_HELP,
      reviewIntervalMonths: INTERVAL_HELP,
      officialSourceUrl: SOURCE_HELP,
      steps: 'The steps in the order they have to be done. Rows can be moved.',
      'steps.title': 'Short and as an action, e.g. “Register your address”.',
      'steps.description': 'What exactly has to be done.',
      'steps.responsibleAuthority': 'The office in charge, e.g. AMS, ÖGK, MA 35, Finanzamt, Magistrat.',
      'steps.timing': 'Deadline or time frame, e.g. “within 3 days”.',
      'steps.requiredDocuments': 'What to bring — one row per document.',
      'steps.requiredDocuments.document': 'e.g. “Passport” or “Tenancy agreement”.',
      'steps.linkedGuideArticle': 'The guide article that explains this step in more detail.',
      'steps.links': 'Forms or pages of the authority for this step.',
      'steps.links.label': 'Link text, e.g. “Registration form (Meldezettel)”.',
      'steps.links.url': 'Full address (https://…).',
      reviewStatus: STATUS_HELP,
    },
    jobs: {
      title: 'Title of the position. Enter it separately for each language.',
      slug: SLUG_HELP,
      organisation: 'Name of the company or institution.',
      city: 'Place of work.',
      bundesland: BUNDESLAND_HELP,
      employmentType: 'Full-time, part-time and so on.',
      description: 'Tasks, requirements, working hours, pay.',
      applyUrl: 'Full address (https://…) or mailto: address that applications go to. The website does not take applications itself.',
      publishedAt: 'Date shown with the position. Empty = today.',
      expiryDate: 'After this date the position disappears from the website by itself.',
      reviewStatus: STATUS_HELP,
    },
    experts: {
      name: 'First and last name as it should appear in the directory. Not translated.',
      slug: 'Part of the web address. Built from the name when the application comes in; has to stay unique.',
      categories: 'Fields of expertise. Visitors can filter by them.',
      bio: 'Short introduction in two to four sentences. Enter it separately for each language.',
      bundesland: 'Federal state the person advises in. The directory can be filtered by it.',
      city: 'Town of the practice or office.',
      languages: 'Languages the person advises in — one row per language.',
      'languages.language': 'e.g. “German”, “Arabic”.',
      contactEmail: 'For internal contact only — shown publicly only once the box next to it is ticked.',
      showEmail: 'Tick only if the person has agreed to it being published.',
      contactPhone: 'For internal contact only — shown publicly only once the box next to it is ticked.',
      showPhone: 'Tick only if the person has agreed to it being published.',
      website: 'Full address (https://…).',
      photo: 'Added by the board after the check — not part of the public application form.',
      consentOnFile: 'Set by the application form when the person has agreed to the data processing. Do not publish without consent.',
      consentDate: 'Date of the consent.',
      verificationStatus: 'Set to “Verified” only once it has been checked that the person is registered with the relevant chamber or authority. Board and administration only.',
      verifiedAt: 'Date of the check. Board and administration only.',
      reviewStatus: STATUS_HELP,
    },
    services: {
      title: 'Name of the service. Enter it separately for each language.',
      slug: SLUG_HELP,
      pillar: 'The focus area the service appears under.',
      summary: 'One or two sentences for the card in the overview.',
      body: 'Detailed description: what is offered and how it works.',
      icon: ICON_HELP,
      image: 'Optional image for the service.',
      targetAudience: 'Who the service is meant for.',
      relatedServices: 'Other services that go with it.',
      reviewStatus: STATUS_HELP,
    },
    pages: {
      title: 'Title of the page. Enter it separately for each language.',
      slug: 'Sets which page of the website is filled. There is currently one: “about” for “About us”. The slug has to be exactly that.',
      layout: 'The content of the page, put together from blocks. Without at least one block the website shows a placeholder. Build it separately for each language.',
      reviewStatus: STATUS_HELP,
    },
    media: {
      alt: 'Required. Describes in one or two sentences what the image shows — for screen readers and search engines. Separately for each language.',
      caption: 'Optional text below the image.',
      credit: 'Photographer or source.',
      consentOnFile: 'For photos with recognisable people: tick only if written consent exists. Do not upload without consent.',
    },
    'contact-submissions': {
      name: 'From the contact form. Do not change.',
      email: 'The person’s reply address.',
      subject: 'Subject from the form.',
      category: 'The matter chosen in the form (e.g. membership, volunteering, idea).',
      message: 'The message, word for word.',
      locale: 'Language the form was filled in — reply in this language.',
      consentGiven: 'The person has agreed to their details being processed.',
      status: 'Set to “Read” or “Archived” once dealt with, to keep the overview.',
      submittedAt: 'Time it came in.',
    },
    categories: {
      name: 'Name of the category as shown in the filter. Enter it separately for each language.',
      slug: 'Part of the filter’s web address. Lowercase letters and hyphens.',
      type: 'What the category is for: news, events, services or experts. It is only offered for selection there.',
    },
    'guide-topics': {
      title: 'Name of the topic, e.g. “Housing”. Enter it separately for each language.',
      slug: SLUG_HELP,
      description: 'One sentence on what this topic is about.',
      icon: ICON_HELP,
      order: ORDER_HELP,
    },
    'service-pillars': {
      title: 'Name of the focus area, e.g. “Education & qualification”. Enter it separately for each language.',
      slug: SLUG_HELP,
      description: 'One or two sentences on the focus area.',
      icon: ICON_HELP,
      colourToken: 'Technical field: name of a colour from the website’s design. Change only after consulting the developers.',
      order: ORDER_HELP,
    },
    'board-members': {
      name: 'First and last name. Not translated.',
      role: 'Function in the association, e.g. “Chairwoman”. Enter it separately for each language.',
      photo: 'Portrait photo, only with the person’s consent.',
      bio: 'Two to three sentences about the person.',
      email: 'Optional.',
      showEmail: 'Tick only if the address may be shown publicly.',
      linkedIn: 'Full address (https://…) of the LinkedIn profile.',
      showLinkedIn: 'Tick only if the link may be shown publicly.',
      order: ORDER_HELP,
    },
    partners: {
      name: 'Name of the organisation.',
      logo: 'Logo as an image from the media library, with a transparent background if possible.',
      url: 'Full address (https://…) of the website. The logo links to it.',
      type: 'Funder, partner or sponsor — decides the group on the partners page.',
      order: ORDER_HELP,
    },
    users: {
      name: 'First and last name. Appears in the notification to the board as “Submitted by”.',
      role: 'Editor: writes drafts and submits them. Board: publishes and archives. Administrator: also users and deleting. Viewer: read only.',
    },
  },

  siteSettings: {
    logo: 'Logo for the header and the admin area. As long as none is uploaded, the lettering “SVÖ” is shown there.',
    logoAlt: 'Light version of the logo for dark areas (e.g. the footer).',
    orgName: 'Name of the association as shown in the footer and in search engines.',
    tagline: 'Short motto below the name.',
    contactGroup: 'Appears in the footer and on the contact page.',
    'contactGroup.address': 'Postal address, several lines.',
    'contactGroup.phone': 'With country code, e.g. +43 1 …',
    'contactGroup.email': 'General contact address of the association.',
    'contactGroup.openingHours': 'For example “Mon–Fri 9 am–5 pm”. Enter it separately for each language.',
    socialLinks: 'Linked profiles in the footer — one row per platform.',
    'socialLinks.platform': 'Decides the icon.',
    'socialLinks.url': 'Full address (https://…) of the profile.',
    seoGroup: 'Applies to all pages that have no SEO details of their own.',
    'seoGroup.defaultTitle': '60 characters at most.',
    'seoGroup.defaultDescription': '160 characters at most. Appears below the title in search engines.',
    'seoGroup.defaultOgImage': 'Image shown when a link is shared. 1200 × 630 pixels.',
    jobResourceLinks: 'Links to AMS, karriere.at and so on. Shown on the jobs page next to the association’s own postings.',
    'jobResourceLinks.label': 'Link text.',
    'jobResourceLinks.url': 'Full address (https://…).',
    'jobResourceLinks.description': 'One sentence on what can be found there.',
    homeGroup: 'Texts and order of the homepage. All fields are optional: an empty field shows the built-in text of that language. Each language is filled in separately — a German text does not replace the Arabic or English one.',
    'homeGroup.sectionOrder.section': 'Which section is in this position.',
    'homeGroup.sectionOrder.enabled': 'Remove the tick to hide the section.',
    'homeGroup.heroHeadline': 'The large headline at the very top.',
    'homeGroup.heroSubline': 'The paragraph below the headline.',
    'homeGroup.heroCtaLabel': 'Text on the button in the top area.',
    'homeGroup.heroCtaHref': 'Internal path, e.g. /contact. Applies to all languages.',
    'homeGroup.statLabels': 'Tiles with figures below the top area. A tile only appears once there are at least three published entries.',
    'homeGroup.statLabels.label': 'Text below the figure, e.g. “Experts”.',
    'homeGroup.statLabels.source': 'What is counted.',
    'homeGroup.helpCards': 'The cards under “How can we help you?”. Empty = built-in cards. A card without a title in a language is not shown in that language.',
    'homeGroup.helpCards.title': 'Heading of the card.',
    'homeGroup.helpCards.description': 'One sentence about the card.',
    'homeGroup.helpCards.href': 'Internal path, e.g. /guide or /contact.',
    'homeGroup.ctaBandHeading': 'Heading of the green band. If something is entered here, the band replaces the two built-in cards “Volunteering” and “Idea”.',
    'homeGroup.ctaBandBody': 'Text below the heading.',
    'homeGroup.ctaBandCtaLabel': 'Text on the button.',
    'homeGroup.ctaBandCtaHref': 'Internal path, e.g. /contact. Applies to all languages.',
    submissionRetentionMonths: 'GDPR: contact requests are deleted after this many months.',
    expertApplicationRetentionMonths: 'GDPR: applications from experts that were never published are deleted after this many months.',
    boardNotificationEmails: 'The email goes to these addresses when the editors submit something for review.',
    'boardNotificationEmails.email': 'One address per row.',
  },

  seo: {
    seo: 'Details for search engines and shared links. Leave empty — the title and short description of the entry are then used.',
    'seo.title': '60 characters at most. Empty = title of the entry.',
    'seo.description': '160 characters at most. Empty = short description of the entry.',
    'seo.ogImage': 'Image when the link is shared. Empty = cover image or default image.',
    'seo.noIndex': 'Tick if the page should not appear in search engines.',
  },
}
